-- 1. Criação e Seleção do Banco de Dados
USE master;
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'dbBancoPIM')
BEGIN
    PRINT('CRIANDO O BANCO DE DADOS dbBancoPIM');
    CREATE DATABASE dbBancoPIM;
END
ELSE
BEGIN
    PRINT('O BANCO dbBancoPIM JÁ EXISTE');
END
GO

USE dbBancoPIM;
GO

-- 2. Remoção de Tabelas (se já existirem, para garantir um script limpo)
IF OBJECT_ID('HISTORICO_DECISOES_IA', 'U') IS NOT NULL DROP TABLE HISTORICO_DECISOES_IA;
IF OBJECT_ID('SOLICITACAO_RESOLUCAO', 'U') IS NOT NULL DROP TABLE SOLICITACAO_RESOLUCAO;
IF OBJECT_ID('RESOLUCAO_SUGERIDA', 'U') IS NOT NULL DROP TABLE RESOLUCAO_SUGERIDA;
IF OBJECT_ID('PRIORIDADE', 'U') IS NOT NULL DROP TABLE PRIORIDADE;
IF OBJECT_ID('PEDIDO', 'U') IS NOT NULL DROP TABLE PEDIDO;
IF OBJECT_ID('SOLICITACAO_SERVICO', 'U') IS NOT NULL DROP TABLE SOLICITACAO_SERVICO;
IF OBJECT_ID('SERVICO', 'U') IS NOT NULL DROP TABLE SERVICO;
IF OBJECT_ID('PRODUTO', 'U') IS NOT NULL DROP TABLE PRODUTO;
IF OBJECT_ID('USUARIO', 'U') IS NOT NULL DROP TABLE USUARIO;
GO

-- 3. Criação das Tabelas

-- Tabela USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_EMPRESARIAL CHAR(4) UNIQUE NOT NULL CHECK (LEN(ID_EMPRESARIAL) = 4), --
    NOME_USUARIO NVARCHAR(60) NOT NULL, --
    EMAIL NVARCHAR(100) NOT NULL, --
    TELEFONE NVARCHAR(20), --
    SENHA NVARCHAR(50) NOT NULL CHECK (LEN(SENHA) >= 5), --
    CARGO NVARCHAR(20) NOT NULL CHECK (CARGO IN ('Administrador', 'Funcionario')) --
);
GO

-- Tabela PRODUTO
CREATE TABLE PRODUTO (
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_PRODUTO NVARCHAR(60) NOT NULL, --
    PRECO_PRODUTO DECIMAL(10,2) NOT NULL, --
    DATA_FABRICACAO DATE NOT NULL, --
    VALIDADE DATE NOT NULL, --
    DISPONIVEL BIT NOT NULL DEFAULT 1 --
);
GO

-- Tabela SERVICO
CREATE TABLE SERVICO (
    ID_SERVICO INT IDENTITY(1,1) PRIMARY KEY,
    DATA_SERVICO DATETIME NOT NULL DEFAULT GETDATE(), --
    DESCRICAO_SERVICO NVARCHAR(100) NOT NULL, --
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIO(ID_USUARIO) --
);
GO

-- Tabela SOLICITACAO_SERVICO (Chamados)
CREATE TABLE SOLICITACAO_SERVICO (
    ID_SOLICITACAO INT IDENTITY(1,1) PRIMARY KEY,
    ID_SERVICO INT NOT NULL FOREIGN KEY REFERENCES SERVICO(ID_SERVICO), --
    ID_USUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIO(ID_USUARIO), --
    DATA_SOLICITACAO DATETIME DEFAULT GETDATE(), --
    DESCRICAO NVARCHAR(255) NOT NULL, --
    STATUS NVARCHAR(20) NOT NULL DEFAULT 'Pendente'
        CHECK (STATUS IN ('Pendente', 'Em andamento', 'Concluido')), --
    PRIORIDADE NVARCHAR(15) NOT NULL DEFAULT 'Média'
        CHECK (PRIORIDADE IN ('Baixa', 'Média', 'Alta')), --
    ANALISE_IA NVARCHAR(255) NULL --
);
GO

-- Tabela PEDIDO
CREATE TABLE PEDIDO (
    ID_PEDIDO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_FORNECEDOR NVARCHAR(100) NOT NULL, --
    ID_PRODUTO INT NOT NULL FOREIGN KEY REFERENCES PRODUTO(ID_PRODUTO), --
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE > 0), --
    DATA_SAIDA DATE NOT NULL, --
    DATA_ENTREGA DATE NOT NULL --
);
GO

-- 4. Criação das Tabelas de Suporte à IA

-- Tabela PRIORIDADE (para IA)
CREATE TABLE PRIORIDADE (
    ID_PRIORIDADE INT IDENTITY(1,1) PRIMARY KEY,
    NOME_PRIORIDADE NVARCHAR(20) NOT NULL, --
    DESCRICAO NVARCHAR(255) NULL --
);
GO

-- Tabela RESOLUCAO_SUGERIDA (para IA)
CREATE TABLE RESOLUCAO_SUGERIDA (
    ID_RESOLUCAO INT IDENTITY(1,1) PRIMARY KEY,
    DESCRICAO NVARCHAR(255) NOT NULL, --
    CATEGORIA_SERVICO NVARCHAR(100) NULL, --
    PRIORIDADE INT NOT NULL FOREIGN KEY REFERENCES PRIORIDADE(ID_PRIORIDADE) --
);
GO

-- Tabela SOLICITACAO_RESOLUCAO (Relacionamento IA)
CREATE TABLE SOLICITACAO_RESOLUCAO (
    ID_SOLICITACAO INT NOT NULL FOREIGN KEY REFERENCES SOLICITACAO_SERVICO(ID_SOLICITACAO), --
    ID_RESOLUCAO INT NOT NULL FOREIGN KEY REFERENCES RESOLUCAO_SUGERIDA(ID_RESOLUCAO), --
    DATA_SUGESTAO DATETIME DEFAULT GETDATE(), --
    PRIMARY KEY (ID_SOLICITACAO, ID_RESOLUCAO) --
);
GO

-- Tabela HISTORICO_DECISOES_IA
CREATE TABLE HISTORICO_DECISOES_IA (
    ID_DECISAO INT IDENTITY(1,1) PRIMARY KEY,
    ID_SOLICITACAO INT NOT NULL FOREIGN KEY REFERENCES SOLICITACAO_SERVICO(ID_SOLICITACAO), --
    PRIORIDADE_SUGERIDA NVARCHAR(20) NOT NULL, --
    RESOLUCAO_SUGERIDA NVARCHAR(255) NULL, --
    DATA_SUGESTAO DATETIME DEFAULT GETDATE(), --
    USUARIO_SUGESTAO INT NULL, --
    OBSERVACAO NVARCHAR(255) NULL --
);
GO

PRINT '=== SCRIPT CONCLUÍDO ===';
PRINT 'Banco de dados dbBancoPIM e tabelas criados com sucesso.';
GO

-- =============================================
-- INSERÇÃO DE DADOS DE TESTE (USUÁRIO)
-- Para testar o login na aplicação .NET
-- =============================================
USE dbBancoPIM;

-- Usuário de Teste: ID: 1324, Senha: 12345
INSERT INTO USUARIO (ID_EMPRESARIAL, NOME_USUARIO, EMAIL, SENHA, CARGO)
VALUES ('1324', 'Usuario Teste', 'teste@empresa.com', '12345', 'Funcionario');